# Generated by Django 5.2 on 2025-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Player'), (2, 'Admin')], default=1, max_length=1),
        ),
    ]
