# Generated by Django 5.2 on 2025-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_difficulty_alter_game_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbank',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
