# Generated by Django 5.2 on 2025-04-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_wordbank_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbank',
            name='category',
        ),
    ]
