# Generated by Django 5.2 on 2025-04-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_wordbank_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
    ]
