# Generated by Django 5.2 on 2025-05-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='joined_at',
        ),
    ]
