# Generated by Django 5.2 on 2025-05-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_player_options_remove_gamehistory_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='user',
            new_name='player',
        ),
    ]
