# Generated by Django 5.2 on 2025-05-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_user_gamehistory_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.wordbank'),
        ),
    ]
