# Generated by Django 5.2 on 2025-05-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_game_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='word',
            field=models.CharField(max_length=30),
        ),
    ]
